services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azure-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: Express

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    ports:
      - "5673:5672"
      - "5300:5300"
    volumes:
      - ./config/emulators/servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    depends_on:
      - azure-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd!"
      SQL_SERVER: azure-sql

  eventhub-emulator:
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    ports:
      - "5674:5672"
    volumes:
      - ./config/emulators/eventhub-config.json:/Eventhubs_Emulator/ConfigFiles/Config.json
    depends_on:
      - azurite
    environment:
      ACCEPT_EULA: "Y"
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
