endpoints:
  - id: test-ping
    path: /test/ping
    methods:
      - GET
    sink: stdout-dev
    message:
      include_body: false
      include_headers: true

  - id: test-webhook
    path: /test/webhook
    methods:
      - POST
    sinks: # Fan-out example
      - rabbitmq-local
      - stdout-dev
    message:
      include_body: true
      include_headers: true

sinks:
  - id: stdout-dev
    type: stdout

  - id: rabbitmq-local
    type: rabbitmq
    settings:
      url_env: RABBITMQ_URL
      exchange: webhooks
      routing_key: events
