endpoints:
  - id: test-ping
    path: /test/ping
    methods:
      - GET
    sink: stdout-dev
    message:
      include_body: false
      include_headers: true

sinks:
  - id: stdout-dev
    type: stdout
